### ISSUE TITLE
not working with socket.io-emitter

### ISSUE THREAD

**Issue by blainejohnson17** [GannettDigital/socket.io-ioredis#3]
the redis channel name is missing trailing '#'
https://github.com/GannettDigital/socket.io-ioredis/blob/master/index.js#L93

from socket.io-emitter:
https://github.com/socketio/socket.io-emitter/blob/master/index.js#L139
and
https://github.com/socketio/socket.io-emitter/blob/master/index.js#L145

**Comment by fracmak** [comment]
Notice https://github.com/GannettDigital/socket.io-ioredis/blob/master/index.js#L92

we push the prefix onto the array before joining with '#', so we generate the same room name the socket.io-emitter is generating

**Comment by blainejohnson17** [comment]
The channel names being generated are:
without room: "prefix#nsp"
with room: "prefix#nsp#room"

should be:
without room: "prefix#nsp#"
with room: "prefix#nsp#room#"

**Comment by fracmak** [comment]
Does it matter though? as long as the search and retrieval names match

**Comment by blainejohnson17** [comment]
like i said, I'm not able to get this working with socket.io-emitter. emitter is publishing to "prefix#nsp#" and "prefix#nsp#room#". But since this lib is subscribing on channel without trailing '#', the emit/broadcast is not received. 

I've confirmed the fix is to add the trailing '#' to the channel name returned by getChannelName

**Comment by fracmak** [comment]
ah, I see

**Comment by fracmak** [comment]
Fixed in #4
